name: Node js project build and deploy to Github pages

on:
  push:
    branches: [ main ]

jobs:
  build-n-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.16.0]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Build the project
      run: | 
            npm ci
            npm run build
    - name: Deploy to pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
          branch: gh-pages 
          folder: dist 
